---
- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana