---
- hosts: nodes
  become: true
  become_method: sudo
  vars:
    AWS_ACCESS_KEY_ID: ""
    POSTGRES_HOST: ""
    POSTGRES_NAME: ""
    POSTGRES_PASSWORD: ""
    AWS_SECRET_ACCESS_KEY: ""

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: Install Docker
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add docker user to a super user
      command: usermod -aG docker "{{ ansible_user }}"

    - name: Restart Docker
      service:
        name: docker
        state: restarted

    - name: Docker pull
      ansible.builtin.command: docker pull kitskat/hr-app:v4

    - name: List content of the working directory
      ansible.builtin.command: pwd && ls

    - name: Echo docker command
      ansible.builtin.command: echo "docker run -d -p 80:5000 -e POSTGRES_HOST={{ POSTGRES_HOST }} -e POSTGRES_USER=kitskatrds -e POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }} -e POSTGRES_DATABASE_NAME=postgres -e TO_ADDRESS=kay.tijani@gmail.com -e SOURCE_ADDRESS=k.tijani0@hotmail.com -e AWS_REGION_NAME=eu-west-1 -e AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }} kitskat/hr-app:v4"

    - name: Running HRAPP Docker instance
      ansible.builtin.command: docker run -d -p 85:5000 -e POSTGRES_HOST=hr-app-project.cku7q07sw3mp.eu-west-1.rds.amazonaws.com -e POSTGRES_USER=kitskatrds -e POSTGRES_PASSWORD="{{ POSTGRES_PASSWORD }}" -e POSTGRES_DATABASE_NAME=postgres -e TO_ADDRESS=kay.tijani@gmail.com -e SOURCE_ADDRESS=k.tijani0@hotmail.com -e AWS_REGION_NAME=eu-west-1 -e AWS_ACCESS_KEY_ID="{{ AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="{{ AWS_SECRET_ACCESS_KEY }}" kitskat/hr-app:v4
