---
- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Debug node_exporter variable
      debug:
        var: node_exporter

    - name: Include prometheus role
      include_role:
        name: prometheus

- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana

  tasks:
    - name: Install Grafana GPG key
      become: yes
      become_user: root
      become_method: sudo
      shell: rpm --import https://packages.grafana.com/gpg.key

    - name: Install Grafana
      become: yes
      become_user: root
      become_method: sudo
      shell: yum install -y https://packages.grafana.com/enterprise/rpm/grafana-enterprise-10.2.3-1.x86_64.rpm
